### ISSUE TITLE
Migrate infrastructure definitions from our Github Actions to Terraform

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/infra#8]
As we're migrating our infrastructure definitions to Terraform, we should also consider moving all the infrastructure definitions being done inside our GitHub Actions to Terraform.

**Comment by teor2345** [comment]
How will we handle infrastructure that needs to change at the same time as a Zebra action or Zebra Rust code?

I'm thinking of some devops bug fix PRs which required all 3 to happen before they would pass CI.

**Comment by gustavovalverde** [comment]
Unscheduling as other issues are being created to track previous actions better.
